version: "3.8"

networks:
  backend:
    driver: overlay

volumes:
  app-source:
  db-data:
#  portainer-data:

services:
#  monitoring:
#    image: portainer/portainer
#    deploy:
#      replicas: 1
#      mode: replicated
#      restart_policy:
#        condition: any
#    ports:
#      - "8000:8000"
#      - "9443:9443"
#    volumes:
#      - type: volume
#        source: portainer-data
#        target: /data
  database:
    image: ghcr.io/mike-prog-lab/wp-deploy/mysql
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 25M
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306"
    networks:
      - backend
  app:
    image: ghcr.io/mike-prog-lab/wp-deploy/mysql
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: any
        max_attempts: 3
      resources:
        limits:
          cpus: '0.4'
          memory: 50M
        reservations:
          cpus: '0.3'
          memory: 25M
      rollback_config:
        parallelism: 1
        failure_action: pause
        order: start-first
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    links:
      - database:mariadb
    volumes:
      - type: volume
        source: app-source
        target: /bitnami/wordpress
        volume:
          nocopy: true
    environment:
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_FIRST_NAME}
      WORDPRESS_LAST_NAME: ${WORDPRESS_LAST_NAME}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_DATABASE_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DATABASE_USER: ${MYSQL_USER}
      WORDPRESS_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      - backend
