version: "3.8"

networks:
  backend:
<<<<<<< Updated upstream
    driver: overlay

volumes:
  app-source:
  db-data:
#  portainer-data:
=======
    driver: bridge
>>>>>>> Stashed changes

services:
  database:
    image: ghcr.io/mike-prog-lab/wp-deploy/mysql
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 250M
    volumes:
      - type: bind
        source: /mnt/mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306"
    networks:
      - backend
  app:
    image: ghcr.io/mike-prog-lab/wp-deploy/wp-app
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: any
        max_attempts: 3
      resources:
        limits:
          cpus: '0.4'
          memory: 50M
        reservations:
          cpus: '0.3'
          memory: 25M
      rollback_config:
        parallelism: 1
        failure_action: pause
        order: start-first
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    volumes:
      - type: bind
        source: /mnt/wp-data
        target: /bitnami/wordpress
    environment:
      MARIADB_HOST: database
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_FIRST_NAME}
      WORDPRESS_LAST_NAME: ${WORDPRESS_LAST_NAME}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_DATABASE_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DATABASE_USER: ${MYSQL_USER}
      WORDPRESS_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      - backend
